AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Py Spotty api'

Parameters:
  DEBUG:
    Type: String
    Default: "true"
    AllowedValues:
      - "true"
      - "false"
  SpotifyClientId:
    Type: String
    Default: '{{resolve:ssm:JafSpotifyClientId:1}}'
    AllowedValues:
      - '{{resolve:ssm:JafSpotifyClientId:1}}'
  SpotifyClientSecret:
    Type: String
    Default: '{{resolve:ssm:JafSpotifySecret:1}}'
    AllowedValues:
      - '{{resolve:ssm:JafSpotifySecret:1}}'
  JwtSecret:
    Type: String
    Default: '{{resolve:ssm:JafJwtSecret:1}}'
    AllowedValues:
      - '{{resolve:ssm:JafJwtSecret:1}}'

Globals:
  Function:
    Timeout: 15
    MemorySize: 128
    Runtime: python3.9
    Environment:
      Variables:
        DEBUG: !Ref DEBUG
        SpotifyClientId: !Ref SpotifyClientId
        SpotifyClientSecret: !Ref SpotifyClientSecret
        JwtSecret: !Ref JwtSecret

Resources:
  HttpApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: v1

  LoadQuizFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: functions/load_quiz.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: SpotifyQuiz
        - DynamoDBCrudPolicy:
            TableName: SpotifyQuizResponse
      Events:
        GetLoadQuiz:
          Type: Api
          Properties:
            Path: /quiz/{type}
            Method: get
            RestApiId: !Ref HttpApiGateway
            RequestParameters:
              - method.request.path.type:
                  Required: true
              - method.request.querystring.id:
                  Required: true
        OptionsLoadQuiz:
          Type: Api
          Properties:
            Path: /quiz/{type}
            Method: options
            RestApiId: !Ref HttpApiGateway
            RequestParameters:
              - method.request.path.type:
                  Required: true

Outputs:
  LoadQuizFunction:
    Description: Python quiz function
    Value: !Ref LoadQuizFunction
  HttpApiGateway:
    Description: Py Api Gateway
    Value: !Ref HttpApiGateway